### ISSUE TITLE
Global header not finished?

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-citylimits#102]
This is what I'm seeing:

![Screen Shot 2019-11-11 at 8 04 16 AM](https://user-images.githubusercontent.com/15877728/68597325-01ae7680-045a-11ea-8238-61486ba6057c.png)

This is what it should be:

![Screen Shot 2019-11-11 at 8 05 42 AM](https://user-images.githubusercontent.com/15877728/68597371-1723a080-045a-11ea-9b8f-5ba21a98765c.png)

**Comment by joshdarby** [comment]
@kaylima The logo not displaying is a known issue that we tried to solve in https://github.com/INN/umbrella-citylimits/pull/86 but didn't have more time to dig into yet before we jumped into the special projects.

**Comment by MirandaEcho** [comment]
Also the two buttons (donate and newsletter) are correct, despite the mockup.
