### ISSUE TITLE
Homepage QA pt. 1

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-citylimits#108]
![city_limits_homepage(top)](https://user-images.githubusercontent.com/15877728/68614543-58c64280-047e-11ea-909b-43694530e90c.png)

![city_limits_homepage(featured-right)](https://user-images.githubusercontent.com/15877728/68615698-d55a2080-0480-11ea-80fd-c84c2bc18b73.png)

**Comment by benlk** [comment]
> fonts
> Dividing lines should be white
> Border-bottom on main nav on homepage

Will be addressed in the PR for #105

> White space between special-projects nav and top of homepage template should be 80px

Most of the homepage layout spacing is built around a variable called `@measure`, which we've defined to be `1.5rem`. This variable controls the spacing of _a lot_ of stuff. If we set the gap here to be `3 * @measure` it'll be `72px`, which is close enough to `80px` and also matches the page's existing visual balance.

I'll use that in the PR for this unless it needs to be something else.

> Make image 90px by 90px

The physical image is 120x120px. In the mockup we have for the desktop-sized homepage, the image is about a quarter of the column width, or is the same size as the images in the special projects navigation. The images in the special projects nav are exactly 60x60.

Which option should we use?

- 90px, which doesn't match the size relative to the special projects menu that was shown in the mockup
- quarter of the column width, which would scale as the column gets wider or smaller
- 60px, to match the special projects menu image size

> Increase space between title and excerpt so that the excerpt flows full-width beneath the image

Not all headlines are long enough or short enough for this to be the case. We could set a min-height on the heading element to match the image size, but if the headline is too long, it will wrap under the image. If we want to avoid that, once we know the width of the image we can constrain the width of the headline so it doesn't creep under.

> Align top of image with top of headline in featured content

In the PR for #105
