### ISSUE TITLE
css is hiding the sub-nav items for the main nav

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-citylimits#110]
Yesterday, Topics had sub-nav items:

![Screen Shot 2019-11-11 at 12 19 11 PM](https://user-images.githubusercontent.com/15877728/68694434-6212e600-0536-11ea-9bbf-7429f192d466.png)

Today, when you roll over Topics, it isn't showing. Also "TOPICS" is going to /category/news ? Not sure if that's correct.

FYI All of the links for the menu are showing on the back-end.

**Comment by benlk** [comment]
This was because the cached version of CSS from the LESS Customizer was using styles from Largo 0.6.1 with markup and javascript from Largo 0.6.4.

Since it was in our go-live todo list #76  to disable the LESS Customizer on prod, I've disabled it here, and the menus are showing up again.
