### ISSUE TITLE
Article QA changes

### ISSUE THREAD

**Issue by joshdarby** [INN/umbrella-citylimits#111]
Main site header:
- [x] Make secondary projects nav, main nav, and header ad zone all 100vw

Article title:
- [x] increase header line height to 1.1

Byline:
- [x] update "author" and "date" titles in byline to use `font-family: roc-grotesk,"Helvetica Neue",Helvetica,Arial,sans-serif;` with 13px font size,`@black` color and matching heights + spacing
- [x] author and date text should be`font-family: neue-haas-grotesk-text,"Helvetica","Helvetia Neue",Arial,sans-serif` font size 16px
- [x] remove `text-transform: uppercase` from text

Social header icons:
- [x] remove plus button in article social sharing
- [x] increase header social icons size to 1.25

Largo related stories widget:
- [x] move byline to bottom
- [x] match byline to homepage ones
- [x] remove date + separator + twitter icon
- [x] move image to right

Article content:
- [x] image caption font size 14px not italicized
- [x] aligned image caption should be same fonts + styles as above
- [x] pullquote element decrease top and bottom padding to 1em

Donation block:
- [x] update donation block `margin-left: calc( ( 100vw - 1170px - 66% ) / -4 )`
- [x] remove text uppercase transform on title
- [x] update title font-size to 26px line-height 36px
- [x] add text-transform uppercase to button
- [x] body text color should be same gray as homepage special projects excerpt text, font size 18px
- [x] button text style should be exactly same as header donate button + hover state should be same too
- [x] add more spacing between button and donation copy

**Comment by benlk** [comment]
> Related stories widget:

In the Largo Related Posts widget, or the Jetpack one?

**Comment by joshdarby** [comment]
@benlk Largo related posts
