### ISSUE TITLE
Special Projects QA

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-citylimits#115]
![citylimits_special_projects_QA](https://user-images.githubusercontent.com/15877728/68795561-788c7080-060e-11ea-8070-769d566999cb.png)

**Comment by joshdarby** [comment]
@kaylima Just a note, the social icons can be removed via an option on the landing page editor
![Screen Shot 2019-11-13 at 3 06 34 PM](https://user-images.githubusercontent.com/18353636/68800007-46d3d380-0627-11ea-892d-23f30c7003bf.png)

**Comment by joshdarby** [comment]
To do:

- [ ] Increase spacing above and below header area
- [ ] Reduce image height
- [ ] Update "special project" font to use `@font-headline`
- [ ] Update project title to use `@font-headline`, 40px font size, and `@black` color
- [ ] Update project description to be `@font-body`, `@grey`, and `line-height: 28px`

**Comment by joshdarby** [comment]
@kaylima Another note, reducing the image height will have the same implications we talked about yesterday when discussing reducing the homepage top story image height. The height will vary based on the image width and aspect ratio.
