### ISSUE TITLE
High priority updates

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#139]
- [x] remove excerpts from homepage secondary featured stories (the three on the right of the main one)
- [x] Fix header ad zone ad breaking out of parent container
- [x] Remove gray overlay from Special projects section
- [x] Can we update the image stretching or does he need to upload different icons? What can we do?
- [x] Troubleshoot broken title and category boxes

**Comment by joshdarby** [comment]
> Troubleshoot broken title and category boxes

This is an issue with the homepage special projects section. When a widget title link is added to the widget, the CSS gets messed up.
