### ISSUE TITLE
Additional site tweaks

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#141]
- [x] Hide horizontal newsletter modal on old series template and author pages
- [x] Reduce the placeholder text size in the input boxes so that text in the newsletter modal in the sidebar doesn't get cut off because of narrow dimensions 
- [x] The Donate and newsletter buttons are getting squished together on desktop windows of certain sizes - CSS fix
- [x] Remove title overlay from black special projects section on homepage, and have it display below the photo instead.
- [x] Remove the gray overlay from the images in that section

**Comment by joshdarby** [comment]
> Remove title overlay from black special projects section on homepage, and have it display below the photo instead.

@MirandaEcho, two questions:

1. Does this styling for the title look ok or does it need to be updated?
2. Do we want to keep or remove the border on the image?

![Screen Shot 2020-01-02 at 3 01 34 PM](https://user-images.githubusercontent.com/18353636/71689762-da489b80-2d70-11ea-847e-2245b1c5cec8.png)

**Comment by joshdarby** [comment]
@MirandaEcho Question about the newsletter signup:

The placeholders in the sidebar version are still cut off even with `font-size: 10px;`. Do we want to update the widths of the elements in there so the form section is wider? It's currently set to 40%.

Here it is at 40% (with updated font size)
![Screen Shot 2020-01-02 at 3 34 39 PM](https://user-images.githubusercontent.com/18353636/71691689-03b7f600-2d76-11ea-9ff3-f5990cbc0071.png)

Here it is at 45% (with updated font size)
![Screen Shot 2020-01-02 at 3 34 18 PM](https://user-images.githubusercontent.com/18353636/71691691-03b7f600-2d76-11ea-89dd-a6d867180b9f.png)

**Comment by kaylima** [comment]
@joshdarby could I please see a full-page screenshot of the 45% version? I want to see how the rest of the article looks with less width and white space to the right. thanks!

**Comment by joshdarby** [comment]
@kaylima Sorry, I probably could have explained that better. The new width percentage is referring to the spacing inside of the actual widget. The widget and spacing outside of it are the same size, it's just that now the "Sign up for our newsletters..." side and the form input side are different widths.

They would be 55% and 45% as opposed to 60% and 45%
