### ISSUE TITLE
CommunityWire Events missing critical info if submitted by logged-out user

### ISSUE THREAD

**Issue by tylermachado** [INN/umbrella-citylimits#26]
**Steps To Reproduce**
0. Ensure you are not logged into City Limits' Wordpress
1. Go to https://citylimits.org/communitywire-home/
2. Click on Submit an Event
3. Fill out the form and click "Submit"

**RESULT**
Now, back logged into Wordpress, the event will submit to the Events Calendar plugin. But it will be missing the Organizer, Venue, and Event Categories. Here's an example of one submitted when logged out: https://citylimits.org/wp-admin/post.php?post=3156926&action=edit

Those things DO appear if the event is submitted by a logged-in user. But City Limits doesn't use Wordpress accounts for readers at the moment.

**EXPECT**
The event should submit with the user-inputted Organizer and Event; the Categories should automatically include CommunityWire Events in addition to whatever category the user selected from the radio buttons. Here's an example of an event that looks good on the backend: https://citylimits.org/wp-admin/post.php?post=3156920&action=edit

**RELEVANT CODE**
Here's where the code that connects the Gravity Form and the Event creation begins: https://github.com/INN/umbrella-citylimits/blob/88c9a157592629e542ae24c97ef895cdee1c1c9c/wp-content/themes/citylimits/inc/communitywire.php#L48

**Comment by tylermachado** [comment]
NOTES UPDATE

Using WP CLI, I have found a potential issue. Note here that `tribe_venue` and `tribe_organizer` have different settings for the "public" and "capability_type" fields, and those are the two that logged-out users can't create. `tribe_event` has those set differently, and logged-out users can create the event itself.

![image](https://user-images.githubusercontent.com/3586466/51137593-e5778400-180c-11e9-82c2-bee1443d98c7.png)

**Comment by MirandaEcho** [comment]
The community events feature is being deprecated
