### ISSUE TITLE
CommunityWire Announcement custom post type not displaying post

### ISSUE THREAD

**Issue by tylermachado** [INN/umbrella-citylimits#27]
**Steps To Reproduce**
1. Go to https://citylimits.org/communitywire-home/
2. Under "Recent Announcements", click on "MBD Community Housing Corp. Receives Non-Profit of the Year Award"

**RESULT**
Page not found error.

**EXPECT**
That announcement should show up. It is present in the backend here: https://citylimits.org/wp-admin/post.php?post=3139740&action=edit

**RELEVANT CODE**
Here's where the code that creates and powers the CommunityWire Announcements custom post type begins: https://github.com/INN/umbrella-citylimits/blob/88c9a157592629e542ae24c97ef895cdee1c1c9c/wp-content/themes/citylimits/inc/communitywire.php#L4

I can't seem to reproduce this locally; everything seems to work there.

**Comment by benlk** [comment]
This looks like it's because the permalink structure hasn't been resaved since the post type was created, which we'd do in https://citylimits.org/wp-admin/options-permalink.php. I'm waiting for a backup to finish running before clicking the "Save Changes" button.

**Comment by benlk** [comment]
Resaving permalinks fixed the problem.
