### ISSUE TITLE
Site Header

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#39]
Custom side header with search, donate, and subscribe buttons. Wireframe and final design TBD

**Comment by MirandaEcho** [comment]
Design completed, this can be estimated and then its ready for @joshdarby

**Comment by MirandaEcho** [comment]
for mobile: the buttons will go side by side where the current Donate link is in the header mockup

**Comment by joshdarby** [comment]
![image (2)](https://user-images.githubusercontent.com/18353636/67412706-c40eaa00-f58d-11e9-880e-557e1e0be3c2.png)
