### ISSUE TITLE
Special projects secondary navigation

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#41]
- Photos are the featured photo for the special projecgt
- Just 4 in mockups as menu items, but should be editable in the future
- Only displays on homepage
- Create as a menu + styling

**Comment by benlk** [comment]
Because of how this integrates with the main nav on mobile, it probably makes sense to wait on this until https://github.com/INN/umbrella-citylimits/issues/40 is completed.

**Comment by benlk** [comment]
Was this resolved with #65?

**Comment by joshdarby** [comment]
@benlk The mobile portion yes, but not the desktop portion.
