### ISSUE TITLE
Homepage: Featured stories section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#42]
- Styling from mockup
- Gray line - estimate and discuss possible approaches
- Customizable stories sections, so that 4th position can be an ad/CTA or another featured story if no ad/CTA widget is selected.

**Comment by benlk** [comment]
<img width="900" alt="Screen Shot 2019-10-10 at 14 25 40 " src="https://user-images.githubusercontent.com/1754187/66595880-dccc9800-eb69-11e9-9f63-7d20feb01585.png">

On the ad stories section:
- query three posts
- output two
- attempt outputting special sidebar, and if that's false, output the remaining post
