### ISSUE TITLE
Homepage: Section 1 and Section 2 content areas

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#43]
- Should be customizable, so contents/categories can be selected based on what needs to be featured on the homepage at any given time
- Title of section also needs to be easily editable
- They will need to control which stories are being featured in that area
- As customizable by client as possible

**Comment by benlk** [comment]
In discussion on the kickoff call, it sounded like we agreed that the easiest way to make these editable would be to make them as widgets, in a widget area taking up the entire homepage bottom.

**Comment by benlk** [comment]
... Looking at the markup, this might be achievable with an unmodified Largo Recent Posts widget and some CSS Grid.

**Comment by benlk** [comment]
<img width="1351" alt="Screen Shot 2019-10-20 at 21 19 20 " src="https://user-images.githubusercontent.com/1754187/67170358-50974d80-f37f-11e9-88ac-01e58e6b93ce.png">

Are we operating on the assumption that they will choose shorter top terms than the ones in this screenshot?
