### ISSUE TITLE
Homepage: Podcast section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#45]
- populated based on podcast category
- Featured so they can select which display if needed, otherwise default to most recent
- Styling based on mockup

**Comment by benlk** [comment]
Widget options:

- [ ] option to show/hide custom excerpt
- [ ] hide byline date, no option
- [ ] no thumbnail, only play icon
- [ ] limit by number
- [ ] limit by category
- [ ] provide docs about how "featured in category" prominence works
- [ ] button/link to see posts with "featured in category" in this category

Widget output:
- [ ] order by featured in category, backfill with newest

<img width="694" alt="Screen Shot 2019-10-23 at 15 39 32 " src="https://user-images.githubusercontent.com/1754187/67428042-5bcec100-f5ab-11e9-8730-bfca013fd4e1.png">
<img width="225" alt="Screen Shot 2019-10-23 at 15 39 42 " src="https://user-images.githubusercontent.com/1754187/67428044-5bcec100-f5ab-11e9-9a96-f9a6f511f269.png">

**Comment by benlk** [comment]
Merged in #80
