### ISSUE TITLE
Homepage: Special project section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#47]
- Photo is featured for special project
- They need to change which special projects are listed here
-  Top 3 featured selected for each
- Border on image might be a nice to have - let's estimate
- May just center the photos in the columns and have a border - again, let's estimate & discuss

**Comment by benlk** [comment]
<img width="693" alt="Screen Shot 2019-10-21 at 10 36 14 " src="https://user-images.githubusercontent.com/1754187/67215019-c1c21980-f3ee-11e9-937c-3c74782b2ff4.png">
<img width="73" alt="Screen Shot 2019-10-21 at 10 36 37 " src="https://user-images.githubusercontent.com/1754187/67215021-c1c21980-f3ee-11e9-9c02-a0a835405df7.png">



On the assumption that "special projects" will _always_ be series, and that series will either have a series landing page or term featured media:

- create custom widget, with options: (4h)
    - choose three series
    - set title
- widget outputs: (2h)
    - series featured image is output with series title overlaid on it
    - 3 posts featured in series output (count not adjustable)
    - top term, headline, excerpt, *not* byline
- other CSS strangeness
    - widgettitle formatting
    - dark background, which we haven't been using elsewhere in this design yet
    - (stretch?) series images spread beyond the border to overlap it — **+1h**
    - (stretch?) pseudoelement border thing like we did for the homepage featured post, behind/beneath the series title — **+1h**
