### ISSUE TITLE
Article: Headline & top area styling

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#50]

**Comment by benlk** [comment]
<img width="555" alt="Screen Shot 2019-10-21 at 10 42 25 " src="https://user-images.githubusercontent.com/1754187/67215461-807e3980-f3ef-11e9-9209-f6c5cae11b59.png">
<img width="281" alt="Screen Shot 2019-10-21 at 10 42 47 " src="https://user-images.githubusercontent.com/1754187/67215484-8bd16500-f3ef-11e9-91e0-95db6d3850c2.png">

**Comment by benlk** [comment]
Merged in #99; is this okay to close?
