### ISSUE TITLE
Pullquote styling

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#53]

**Comment by benlk** [comment]
<img width="273" alt="Screen Shot 2019-10-21 at 10 43 31 " src="https://user-images.githubusercontent.com/1754187/67215577-b15e6e80-f3ef-11e9-9d98-7511fa1ac46f.png">
<img width="651" alt="Screen Shot 2019-10-21 at 10 43 49 " src="https://user-images.githubusercontent.com/1754187/67215578-b15e6e80-f3ef-11e9-920b-aaeafd3a0093.png">

We can probably copy some work on this regarding the `"` symbols from https://github.com/INN/umbrella-workdayminn/pull/22

These mockups don't show style variants like Workday did, so we can unregister the WP Core "large" variation https://developer.wordpress.org/block-editor/developers/filters/block-filters/ using the JS methods for [WP pre-5.3](https://make.wordpress.org/core/2019/09/24/new-block-apis-in-wordpress-5-3/).

For a bonus hour, we'll want to register the theme's stylesheet colors as colors for the block editor to use: https://github.com/INN/umbrella-workdayminn/pull/22/files?file-filters%5B%5D=.less&file-filters%5B%5D=.php#diff-dab89d58eef4f1c3e61551b7ae5f5b12

**Comment by joshdarby** [comment]
> These mockups don't show style variants like Workday did, so we can unregister the WP Core "large" variation https://developer.wordpress.org/block-editor/developers/filters/block-filters/ using the JS methods for WP pre-5.3.

@benlk 5.3 isn't out until 11/12/19 at the earliest, so that part might have to wait.

**Comment by kaylima** [comment]
Roc Grotesk ExtraBold, 32px, black (the quotation marks are #E62322)
