### ISSUE TITLE
Article: Custom Donation block

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#54]
Editable custom block (see mockup) for donation CTA

**Comment by joshdarby** [comment]
Following questions are under the assumption that this will be a brand new custom Gutenblock.

- [ ] Does the `Donate` button copy need to be editable, or just the title and content?
- [ ] Will this always only be right/left aligned, or is it safe to assume it will be used full-width at some point?

![Screen Shot 2019-10-21 at 10 48 07 AM](https://user-images.githubusercontent.com/18353636/67215904-48c3c180-f3f0-11e9-9429-bf2c30dafe68.png)

**Comment by benlk** [comment]
We'll need to provide styles for aligned right/left/center/none by default, but we can include in the block's code that it doesn't support wide or full widths if we don't want to cover those.

Does the donation link itself need to be editable?

**Comment by kaylima** [comment]
Yes, donate link needs to be editable (for CTA testing purposes).

This can almost be thought of as a pullquote style. Will not be full-width. (we'll need something else for that.)
