### ISSUE TITLE
SCAIP Ad widget styles

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#55]

**Comment by benlk** [comment]
The in-article styles for SCAMP widgets don't match the homepage styles for SCAMP widgets, so this does not duplicate https://github.com/INN/umbrella-citylimits/issues/44

**Comment by benlk** [comment]
In same PR #79 as #44, using some mixins from #67 for the thin lines.

**Comment by benlk** [comment]
#79 doesn't implement the thin lines yet; waiting on ad configuration before adding those in, because not having ads load makes it harder to test the styles.
