### ISSUE TITLE
Special Projects: Top section styling

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#68]

**Comment by benlk** [comment]
<img width="783" alt="Screen Shot 2019-10-21 at 12 30 43 " src="https://user-images.githubusercontent.com/1754187/67224178-a7903780-f3fe-11e9-8938-33e213736aa8.png">
<img width="277" alt="Screen Shot 2019-10-21 at 12 30 57 " src="https://user-images.githubusercontent.com/1754187/67224179-a7903780-f3fe-11e9-95d8-2f00e9fa4111.png">

**Comment by benlk** [comment]
This was merged in #88; is it okay to close?
