### ISSUE TITLE
Special projects: content areas

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#71]
- They choose a photo, then list of links
    - Links may be internal or external
    - Content areas should be optional
    - Three total:
        - White background 3 columns
        - Tan background 2 columns
        - White 1 column, photo on bottom, 2 lists
(see mockup)

**Comment by benlk** [comment]
That's these three sections of the page, right?

<img width="404" alt="Screen Shot 2019-10-21 at 12 33 30 " src="https://user-images.githubusercontent.com/1754187/67224363-05bd1a80-f3ff-11e9-9142-ef34ffb0e2a1.png">

**Comment by kaylima** [comment]
I believe so, @benlk @MirandaEcho can you confirm?

Please note that the idea for the special projects is that they will all be different and they'll want to choose from different content sections/options for putting together the landing pages. I think this needs to be a larger conversation of how we want to build this that works with their workflow. FYI @joshdarby

**Comment by benlk** [comment]
Notes upon the structure of the special projects page:

![Special Projects-Desktop](https://user-images.githubusercontent.com/1754187/67243223-197b7780-f425-11e9-96ff-5bab8475be01.png)

If we take the side-by-side presentation of the arbitrary content in #71, the second newsletter signup widget, and the survey in #72, and replace that side-by-side presentation with the same content spanning the full column of the page, then we can expose the layout of this whole page to the editors as a single widget area encompassing the entire page from after Latest News #70 to Featured News #73. That gives them maximum layout flexibility in a single interface.

Down the road, we're probably going to want to change Largo's series landing pages to support the Block Editor, and redefine all its current content-presentation mechanisms as Blocks, so that editors have a nice WYSIWYG option for editing series landing pages.

**Comment by MirandaEcho** [comment]
Featured content at bottom of special project:
- Archive (avoid duplication if possible)
- Can the section be optional? Or switch to related content for newer projects? (there will be new projects that don't have a ton of content yet)

**Comment by benlk** [comment]
Mockup of plain widget-based bottom section is too large for GitHub: https://files.slack.com/files-pri/T03G0JQPT-FPG6W8QJD/download/special-projects-single-column.png

@kaylima what do you need for this for an internal UX review?

**Comment by kaylima** [comment]
@ben anything related to back-end workflow. I'll want to be able to recreate an existing project to see what questions/issues/concerns pop up.

**Comment by benlk** [comment]
The general process for creating a series landing page:
1. go to http://staging.citylimits.flywheelsites.com/wp-admin/edit-tags.php?taxonomy=series and create a series — I have created for http://staging.citylimits.flywheelsites.com/wp-admin/term.php?taxonomy=series&tag_ID=35184&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dseries%26post_type%3Dpost%26s%3Dtest use in this example.
2. go to http://staging.citylimits.flywheelsites.com/wp-admin/edit.php?post_type=cftl-tax-landing and create a new landing page — I have created http://staging.citylimits.flywheelsites.com/wp-admin/post.php?post=5448600&action=edit
3. Largo creates the widget area with the appropriate name.
4. In http://staging.citylimits.flywheelsites.com/wp-admin/widgets.php find the widget area named "Series Landing Page for Test Series: Footer" and add widgets to it. When the template is made, these widgets will fill the widget area marked in purple in the annotated mockup above, appearing in a single-column fashion that matches their order in the widget admin.
5. Changes are reflected at http://staging.citylimits.flywheelsites.com/series/test-series-with-landing-page/

The next steps in the build process are:
1. create a template that's specific to the "Special Projects" landing pages, containing: 
    - the special header in #68
    - the project menu in #69
    - the latest-news section in #70
    - this widget area
    - the additional-stories section in #73
2. Create widgets to populate the widget area
    - the content widgets for #71
    - styles for surveys for #72 
    - newsletter signup widget styles, #49 

Regarding the special-content widgets for #71, we've decided that we don't want to rely on users writing specific HTML inside Custom HTML widgets, so I'm wondering if we could create a modified Text Widget that presents three TinyMCE content editors to the user: one for each section of that area. They'd display in the Widget editor one above the other, and we could include notes or diagrams explaining their order on mobile and desktop.

**Comment by MirandaEcho** [comment]
Is there still a question here, or can we estimate it?

**Comment by joshdarby** [comment]
> Is there still a question here, or can we estimate it?

@MirandaEcho I think we can go ahead and estimate the individual issues @benlk detailed above

**Comment by benlk** [comment]
I moved #73 to the "new widgets" section of the above list, based on what Miranda was saying in that issue.

**Comment by MirandaEcho** [comment]
Can this be closed since we have individual issues for these?  Also, we do have the approval to do the single-column layout (Ben's mockup) rather than side-by-side widgets from the original mockup
