### ISSUE TITLE
Survey styling

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#72]
Form styling for Gravity Forms - see special project mockup

**Comment by benlk** [comment]
<img width="770" alt="Screen Shot 2019-10-21 at 10 23 16 " src="https://user-images.githubusercontent.com/1754187/67213904-d43b5380-f3ec-11e9-8650-9fb7c8231771.png">

The survey is just the left-hand portion of this section of the page.

What can we assume about the content of these surveys?
- Will we need to provide styles for both checkboxes and radio inputs? The design in the mockup shows checkboxes, but "most important issue" is language that reflects a single choice, which would use a radio button.
- Will we need to provide styles for textareas as well as the `input type="text"` shown in the mockups?

Parts of design thus far:
- dummy content for testing on dev and staging (2h)
- custom checkbox/radio (2h)
- misc other styles (2h)
    - list item fonts/color
    - label fonts/color
    - common widget title style (create a mixin from the homepage styles added in https://github.com/INN/umbrella-citylimits/pull/67)
    - submit button

**Comment by kaylima** [comment]
> Will we need to provide styles for both checkboxes and radio inputs? The design in the mockup shows checkboxes, but "most important issue" is language that reflects a single choice, which would use a radio button.
> Will we need to provide styles for textareas as well as the input type="text" shown in the mockups?

^ Yes and yes

**Comment by joshdarby** [comment]
@kaylima @MirandaEcho Since these are just forms from Gravity Forms, we'll need a way to distinguish these "surveys" from other normal forms. Is it too complicated to have users set the `CSS Class Name` field to `survey` under Form Settings for each form? If so, we will probably need to create a new survey specific widget.

**Comment by joshdarby** [comment]
> I think that’s fine. Let’s call it something more specific, like series-survey, if we can or special-projects-survey

From @kaylima on Slack.
