### ISSUE TITLE
Go-live configuration items

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-citylimits#76]
- [ ] disable the LESS/CSS Customizer (#62)
- [ ] populate the homepage with widgets
- [ ] remove newsletter widget from "Header Ad Zone" widget area
- [ ] clear inactive widgets from inactive sidebars

**Comment by MirandaEcho** [comment]
- [ ] complete Facebook Domain Verification

**Comment by benlk** [comment]
- [ ] homepage widgets to reflect designs
- [ ] article widgets to reflect designs
- [ ] change Mapping The Future template and widgets to match

**Comment by benlk** [comment]
From #38:

> NOTE FOR DEVELOPMENT:
> 
> let's explore the Jetpack feature for hiding widgets when we set up the pre-footer area for the newsletter signup (specifically for articles/posts)

**Comment by benlk** [comment]
For the footer newsletter signup widget:

- [ ] In Appearance > Theme Options > Layout > Sidebar Options, enable the footer sidebar

**Comment by MirandaEcho** [comment]
- [ ] Double check donate and newsletter links in header to make sure they're correct

**Comment by joshdarby** [comment]
- [ ] `Checked on Frontend?` CL Mailchimp Settings field
