### ISSUE TITLE
Play icon appears in homepage special projects stories

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-citylimits#87]
These should not be displaying the play-icon markup:

<img width="378" alt="Screen Shot 2019-11-04 at 12 41 32 " src="https://user-images.githubusercontent.com/1754187/68143914-79335180-ff00-11e9-8ff0-543c2f84613d.png">

Something in that widget is setting off this conditional:

https://github.com/INN/umbrella-citylimits/blob/5a2f4afec038e2f1b9c73e7f5997c5f7cec36eb0/wp-content/themes/citylimits/partials/widget-content.php#L16-L23

**Comment by benlk** [comment]
With reference to https://github.com/INN/largo/issues/1832, we can fix this in this theme by reimplementing `largo_render_template()`, with the patch, in this child theme, and then using that `citylimits_render_template()` in this theme wherever we would have used `largo_render_template()`.

**Comment by joshdarby** [comment]
Looks like the fixes listed in these comments https://github.com/INN/largo/issues/1832#issuecomment-553457658, https://github.com/INN/largo/issues/1832#issuecomment-553459198 don't make a difference. 😕 

Looking into why.
